server:
  port: 12345
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: 127.0.0.1 # 服务注册中心IP地址
  client:
    # 是否向eureka注册自身服务
    register-with-eureka: true
    #是否检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/